config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'admins#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :home, only: :index
  resources :trucks
  resources :drivers
  resources :routes
  resources :cargos
  resources :model_types
  resources :trains
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  belongs_to :truck

  validates :description, presence: true
  validates :title, presence: true
  validates :reference_number, presence: true
  validates :value, presence: true

  def truck_name
    truck.license_plate
  end
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  load_and_authorize_resource

  helper_method :cargos, :cargo

  def index
    model_attributes(Cargo)
    @model_attributes.push('truck_name')
  end

  def new
    @cargo = Cargo.new
  end

  def create
    @cargo = Cargo.new(cargo_params)

    if @cargo.save
      redirect_to cargos_path, notice: "#{cargo.title} successfully created"
    else
      render 'new'
    end
  end

  def edit
    @cargo = Cargo.find(params[:id])
  end

  def update
    @cargo = Cargo.find(params[:id])
    if @cargo.update(cargo_params)
      redirect_to cargos_path, notice: "#{cargo.title} successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    cargo = Cargo.find(params[:id])
    cargo.destroy

    redirect_to cargos_path, notice: "#{cargo.title} successfully deleted"
  end

  private
  def cargo_params
    params.require(:cargo).permit(:description, :title, :reference_number, :value, :paid, :truck_id)
  end

  def cargos
    @cargos ||= Cargo.all
  end

  def cargo
    @cargo
  end
end

app/views/cargos/_form.html.slim
= form_with model: cargo, local: true do |f|
  = render partial: 'shared/error', locals: { model: cargo }
  p
    = f.label :description
    br
    = f.text_field :description
  p
    = f.label :title
    br
    = f.text_field :title
  p
    = f.label :reference_number
    br
    = f.text_field :reference_number
  p
    = f.label :value
    br
    = f.text_field :value
  p
    = f.label :truck
    br
    = f.collection_select :truck_id, Truck.all, :id, :license_plate, include_blank: 'Select a Truck'
  p
    = f.label :paid
    br
    = f.radio_button(:paid, true)
    = label_tag(:paid, "true")
    br
    = f.radio_button(:paid, false)
    = label_tag(:paid, "false")
  p
    = f.submit

app/views/cargos/edit.html.slim
h1 Editing Cargo
= render 'form'
= link_to 'Back', cargos_path

app/views/cargos/index.html.slim
h1 Cargos Index
= link_to 'New cargo', new_cargo_path
= render partial: 'shared/notice'
= render partial: 'shared/common_table', locals: { model_attributes: @model_attributes, data_collection: cargos }

app/views/cargos/new.html.slim
h1 Create cargo
= render 'form'
= link_to 'Back', cargos_path