config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'admins#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :home, only: :index
  resources :trucks
  resources :drivers
  resources :routes
  resources :cargos
  resources :model_types
  resources :trains
end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :driver_trucks, dependent: :destroy
  has_many :drivers, through: :driver_trucks
  has_many :cargos, dependent: :destroy
  has_many :routes, dependent: :destroy
  belongs_to :model_type

  validates :license_plate, presence: true
  validates :capacity, presence: true
  enum status: [ :active, :inactive, :servicing ]

  validates :status, inclusion: { in: Truck.statuses.keys }

  def driver_name
    drivers.map(&:name).join(', ')
  end

  def route_name
    routes.map(&:name).join(', ')
  end

  def cargo_name
    cargos.map(&:title).join(', ')
  end

  def model_type_name
    model_type.name
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  load_and_authorize_resource

  helper_method :trucks, :truck

  def index
    model_attributes(Truck)
    @model_attributes.push('driver_name', 'route_name', 'cargo_name', 'model_type_name')
  end

  def new
    @truck = Truck.new
  end

  def create
    @truck = Truck.new(truck_params)

    if @truck.save
      redirect_to trucks_path, notice: "#{truck.license_plate} successfully created"
    else
      render 'new'
    end
  end

  def edit
    @truck = Truck.find(params[:id])
  end

  def update
    @truck = Truck.find(params[:id])

    if @truck.update(truck_params)
      redirect_to trucks_path, notice: "#{truck.license_plate} successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    truck = Truck.find(params[:id])
    truck.destroy

    redirect_to trucks_path, notice: "#{truck.license_plate} successfully deleted"
  end

  private
  def truck_params
    params.require(:truck).permit(:license_plate, :capacity, :color, :service_date, :status, :model_type_id)
  end

  def trucks
    @trucks ||= Truck.all
  end

  def truck
    @truck
  end
end

app/views/trucks/_form.html.slim
= form_with model: truck, local: true do |f|
  = render partial: 'shared/error', locals: { model: truck }
  p
    = f.label :license_plate
    br
    = f.text_field :license_plate
  p
    = f.label :capacity
    br
    = f.text_field :capacity
  p
    = f.label :model_type
    br
    = f.collection_select :model_type_id, ModelType.all, :id, :name, include_blank: 'Select a model'
  p
    = f.label :color
    br
    = f.text_field :color
  p
    = f.label :service_date
    br
    = f.date_field :service_date
  p
    = f.label :status
    br
    = f.radio_button(:status, "active")
    = label_tag(:status, "active")
    br
    = f.radio_button(:status, "inactive")
    = label_tag(:status, "inactive")
    br
    = f.radio_button(:status, "servicing")
    = label_tag(:status, "servicing")
  p
    = f.submit

app/views/trucks/edit.html.slim
h1 Editing Truck
= render 'form'
= link_to 'Back', trucks_path

app/views/trucks/index.html.slim
h1 Trucks Index
= link_to 'New truck', new_truck_path
= render partial: 'shared/notice'
= render partial: 'shared/common_table', locals: { model_attributes: @model_attributes, data_collection: trucks }

app/views/trucks/new.html.slim
h1 Create truck
= render 'form'
= link_to 'Back', trucks_path