config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'admins#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :home, only: :index
  resources :trucks
  resources :drivers
  resources :routes
  resources :cargos
  resources :model_types
  resources :trains
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  helper_method :train

  before_action :train_params, only: [:create, :update]

  def index
    @trains = TrainApi.new.index
  end

  def new
    @train = OpenStruct.new({"active": false})
  end

  def create
    response = TrainApi.new.create(train_params)

    if response.success?
      redirect_to trains_path, notice: response["message"]
    else
      flash["errors"] = response["errors"]
      @train = OpenStruct.new(params[:train])
      render "new"
    end
  end

  def edit
    flash["errors"] = nil
    @train = OpenStruct.new(TrainApi.new.show(params[:id]))
  end

  def update
    response = TrainApi.new.update(params[:id], train_params)

    if response.success?
      redirect_to trains_path, notice: response["message"]
    else
      flash["errors"] = response["errors"]
      @train = OpenStruct.new(params[:train])
      render "edit"
    end
  end

  def destroy
    response = TrainApi.new.destroy(params[:id])

    if response.success?
      redirect_to trains_path, notice: response["message"]
    else
      redirect_to trains_path, notice: "Oops, Something went wrong!"
    end
  end

  private
  def train_params
    params.require(:train).permit(:name, :train_model_name, :number_of_cars, :max_weight_capacity, :active)
  end

  def train
    @train
  end
end

app/views/trains/_error.html.slim
- if flash["errors"]
  #error_explanation class="alert alert-danger"
    h2
      = pluralize(flash["errors"][0].values.flatten.length, "error")
      |  prohibited this train from being saved:
    ul
      - flash["errors"][0].each do |name, messages|
        - messages.each do |message|
          li
            = name.humanize
            | #{" "}
            = message

app/views/trains/_form.html.slim
= form_for :train, method: method, url: url, local: true do |f|
  = render partial: "error", locals: flash
  p
    = f.label :name
    br
    = f.text_field :name, value: train["name"]
  p
    = f.label :train_model_name
    br
    = f.text_field :train_model_name, value: train["train_model_name"]
  p
    = f.label :number_of_cars
    br
    = f.text_field :number_of_cars, value: train["number_of_cars"]
  p
    = f.label :max_weight_capacity
    br
    = f.text_field :max_weight_capacity, value: train["max_weight_capacity"]
  p
    = f.label :active
    br
    = f.radio_button(:active, true)
    = label_tag(:active, "true")
    br
    = f.radio_button(:active, false)
    = label_tag(:active, "false")
  p
    = f.submit(value: "#{submit_text} Train")

app/views/trains/edit.html.slim
h1 Editing Train
= render partial: 'form', locals: { submit_text: "Update", url: train_path, method: :patch }
= link_to 'Back', trains_path

app/views/trains/index.html.slim
h1 Trains Index
= link_to 'New train', new_train_path
= render partial: 'shared/notice'

table class="table"
  thead
    tr
      - ["id", "name", "train_model_name", "number_of_cars", "max_weight_capacity", "active"].each do |attribute|
        th(scope="col")= attribute.humanize
      - if current_admin.present?
        th scope="col" Actions
  - if @trains.count > 0
    tbody
      - @trains.each do |train|
        tr
          - @trains.first.keys.each do |attribute|
            td = train[attribute]
          - if current_admin.present?
            td
              a(class="btn btn-primary" href=edit_train_path(train["id"]) role="button") Edit
              a(class="btn btn-mini btn-danger" rel="nofollow" data-method="delete" data-confirm="Are you sure?" href=train_path(train["id"])) Delete

app/views/trains/new.html.slim
h1 Create train
= render partial: 'form', locals: { submit_text: 'Create', url: trains_path, method: :post }
= link_to 'Back', trains_path