config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :admins
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'admins#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :home, only: :index
  resources :trucks
  resources :drivers
  resources :routes
  resources :cargos
  resources :model_types
  resources :trains
end

app/views/shared/_common_table.html.slim
table class="table"
  thead
    tr
      - model_attributes.each do |model_attribute|
        th scope="col" = model_attribute.humanize

      - if current_admin.present?
        th scope="col" Actions
  tbody
    - data_collection.each do |data|
      tr
        - model_attributes.each do |model_attribute|
          td = data.send(model_attribute)

        - if current_admin.present?
          td
            a(class="btn btn-primary" href=edit_polymorphic_path(data) role="button") Edit
            a(class="btn btn-mini btn-danger" rel="nofollow" data-method="delete" data-confirm="Are you sure?" href=polymorphic_path(data)) Delete

app/views/shared/_error.html.slim
- if model.errors.any?
  #error_explanation class="alert alert-danger"
    h2
      = pluralize(model.errors.count, "error")
      |  prohibited this #{model.class} from being saved:
    ul
      - model.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_header.html.slim
a(class="navbar-brand" href="/")
  | Home

#navbarSupportedContent.collapse.navbar-collapse
  ul.navbar-nav.mr-auto
    - ["trains", "trucks", "drivers", "routes", "cargos", "model_types"].each do |item|
      li.nav-item
        a(class="nav-link" href="/#{item}")
          = item.titleize

  ul.navbar-nav
    li.nav-item
      - if current_admin.present?
        = link_to "View admins", admins_path
        = " Logged in as #{current_admin.email}. "
        = link_to "Log Out", logout_path
      - else
          = link_to "Sign Up", signup_path
          |  or#{" "}
          = link_to "Log In", login_path

app/views/shared/_notice.html.slim
- if notice
  .alert.alert-success
    = notice